#Src/Project/Domain/object_parameters.py

# ぶつかりおじさんのパラメータ
OJISAN_ID = 1 # ID範囲: 1~3
OJISAN_HP = 2
OJISAN_DAMAGE = 10
OJISAN_IS_JUMPABLE = False
OJISAN_ADD_SCORE = 500
OJISAN_SUB_SCORE = 500

# ぶつかりおじさん（強）のパラメータ
STRONG_OJISAN_ID = 4  # ID範囲: 4~6
STRONG_OJISAN_HP = 3
STRONG_OJISAN_DAMAGE = 20
STRONG_OJISAN_IS_JUMPABLE = False
STRONG_OJISAN_ADD_SCORE = 1000
STRONG_OJISAN_SUB_SCORE = 1000

# 歩きスマホのパラメータ
SMARTPHONE_USER_ID = 11  # ID範囲: 11~14
SMARTPHONE_USER_HP = 1
SMARTPHONE_USER_DAMAGE = 10
SMARTPHONE_USER_IS_JUMPABLE = False
SMARTPHONE_USER_ADD_SCORE = 300
SMARTPHONE_USER_SUB_SCORE = 300

# ふろキャン界隈のパラメータ
FUROCAN_KAIWAI_ID = 16  # ID範囲: 16~19
FUROCAN_KAIWAI_HP = 2
FUROCAN_KAIWAI_DAMAGE = 20
FUROCAN_KAIWAI_IS_JUMPABLE = False
FUROCAN_KAIWAI_ADD_SCORE = 1000
FUROCAN_KAIWAI_SUB_SCORE = 1000

# ２マスのキャラ（キャリーケースを持った人）のパラメータ
CARRY_CASE_PERSON_ID = 21  # ID範囲: 21~24
CARRY_CASE_PERSON_HP = 2
CARRY_CASE_PERSON_DAMAGE = 10
CARRY_CASE_PERSON_IS_JUMPABLE = False
CARRY_CASE_PERSON_ADD_SCORE = 0
CARRY_CASE_PERSON_SUB_SCORE = 500

# 4人組のやんちゃ集団のパラメータ
YANCHA_GROUP_ID = 26
YANCHA_GROUP_HP = 2
YANCHA_GROUP_DAMAGE = 10
YANCHA_GROUP_IS_JUMPABLE = False
YANCHA_GROUP_ADD_SCORE = 1000
YANCHA_GROUP_SUB_SCORE = 1000

# 一般人のパラメータ
CIVILIAN_ID = 41  # ID範囲: 41~45
CIVILIAN_HP = 1
CIVILIAN_DAMAGE = 3
CIVILIAN_IS_JUMPABLE = False
CIVILIAN_ADD_SCORE = 0
CIVILIAN_SUB_SCORE = 500

# バナナのパラメータ
BANANA_ID = 51
BANANA_HP = 1
BANANA_DAMAGE  = 10
BANANA_IS_JUMPABLE = True
BANANA_ADD_SCORE = 0
BANANA_SUB_SCORE = 300

# カラーコーン
COLOR_CONE_ID = 56
COLOR_CONE_HP = 1
COLOR_CONE_DAMAGE = 10
COLOR_CONE_IS_JUMPABLE = False
COLOR_CONE_ADD_SCORE = 0
COLOR_CONE_SUB_SCORE = 300

# ２マスの障害物（キャリーケース）のパラメータ
CARRY_CASE_OBSTACLE_ID = 61
CARRY_CASE_OBSTACLE_HP = 1
CARRY_CASE_OBSTACLE_DAMAGE = 5
CARRY_CASE_OBSTACLE_IS_JUMPABLE = False
CARRY_CASE_OBSTACLE_ADD_SCORE = 0
CARRY_CASE_OBSTACLE_SUB_SCORE = 300